version: 2
jobs:
  build:
    working_directory: ~/vts-masker
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          PGHOST: 127.0.0.1
          DATABASE_URL: postgres://masker@127.0.0.1/masker_test
          RAILS_ENV: test
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: masker
          POSTGRES_DB: masker_test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: vts-masker-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: vts-masker-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - type: shell
        command: bundle exec rspec
